ifpe-cti/vaidbike

- .gitignore
- src/main/resources/model/Locador.java
- src/main/resources/model/Locatario.java
criação das classes locador e locatario.
> primeiro commit para teste de classes.

- src/main/java/model/interfacesDao/UsuarioDao.java
Adicionado a Interface UsuarioDao
> Conforme a issue #10

- src/main/java/model/classes/Endereco.java
- src/main/java/model/hibernate/UsuarioHibernate.java
- src/main/java/model/interfacesDao/Dao.java
- src/main/java/model/interfacesDao/UsuarioDao.java
Foram implementados os métodos da classe UsuarioHibernate.
> Conforme Issue #12.

- .gitignore
- pom.xml
- src/main/java/model/hibernate/UsuarioHibernate.java
- src/test/java/model/hibernate/UsuarioHibernateIT.java
Adicionado a dependência do DBUnit.
> Conforme a Issue #33

- src/main/java/model/classes/Endereco.java
- src/main/java/model/classes/Locacao.java
- src/main/java/model/classes/Pagamento.java
- src/main/java/model/hibernate/PagamentoHibernate.java
- src/main/java/model/hibernate/UsuarioHibernate.java
- src/main/java/model/interfacesDao/PagamentoDao.java
- src/main/java/model/interfacesDao/UsuarioDao.java
- src/main/resources/hibernate.cfg.xml
Adicionado classe Pagamento Hibernate.
> Conforme a Issue #20

- src/main/java/UsuarioModel.java
Criado classe UsuarioModel para implementar as devidas validações.
> Conforme a Issue #13

- src/main/java/model/hibernate/UsuarioHibernate.java
- src/main/java/model/validation/UsuarioModel.java
- src/main/java/model/validation/ValidarCpf.java
Criado classe UsuarioModel com as devidas validações.
> Conforme Issue #13

- src/main/java/model/validation/PagamentoModel.java
Adicionado classe Pagamento Model.
> Conforme a Issue #21

- src/main/java/model/classes/Endereco.java
- src/main/java/model/classes/Usuario.java
- src/main/java/view/TesteMain.java
Persistência de dados da classe usuário com a classe endereço está funcionando, devido a modificação da anotação da classe usuário.
> Conforma a Issue #50

- src/main/java/model/classes/Bike.java
- src/main/java/model/classes/Endereco.java
- src/main/java/model/classes/Locacao.java
- src/main/java/model/classes/Pagamento.java
- src/main/java/model/classes/Usuario.java
- src/main/java/model/hibernate/UsuarioHibernate.java
- src/main/java/model/validation/UsuarioModel.java
- src/main/java/view/TesteMain.java
O problema foi resolvido ao adicionar uma bike ao usuário.
> Conforme a Issue #52

- src/main/java/model/classes/Pagamento.java
- src/main/java/model/classes/Usuario.java
- src/main/java/model/hibernate/LocacaoHibernate.java
- src/main/java/view/TesteMain.java
Adicionado a classe LocacaoHibernate,falta alguns métodos e reparações na classe.
> Conforme a Issue #16

- src/main/java/controller/PagamentoController.java
- src/main/java/view/TesteMain.java
- src/main/resources/hibernate.cfg.xml
Adicionado a classe Pagamento Controller
> Conforme a Issue #22

- src/main/java/model/hibernate/LocacaoHibernate.java
- src/main/java/model/hibernate/UsuarioHibernate.java
- src/main/java/model/interfacesDao/LocacaoDao.java
- src/main/java/model/validation/LocacaoModel.java
- src/main/java/model/validation/UsuarioModel.java
- src/main/java/view/TesteMain.java
A classe LocacaoModel foi adicionada. As alterações foram feitas nas classes LocacaoHibernate e LocacaoDao. A classe LocacaoHibernate foi adicionado commit() para atualização do banco de dados no método deletar, já na Interface LocacaoDao foi adicionado mais um método.
> Conforme a Issue #17 e outras alterações

- src/main/java/controller/md5/MD5_Criptografia.java
Adicionado a classe de criptografia
> Conforme a Issue #58

- src/main/java/controller/LocacaoController.java
Falta construção dos métodos da classe LocacaoController.
> Conforme a Isseu #18

- src/main/java/br/edu/ifpe/model/classes/Bike.java
Tirado os espaçamentos em branco e sets desnecessários
> #63 Corrigida as anotações e adicionado os méotodos

- src/main/java/br/edu/ifpe/model/classes/Bike.java
- src/main/java/br/edu/ifpe/model/classes/Endereco.java
Corrigida as anotações e métodos equals,hashCode e toString da classe Endereco.
> #65 Corrigida as anotações e métodos da classe Endereco

- src/main/java/br/edu/ifpe/model/classes/Pagamento.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/resources/hibernate.cfg.xml
Corrigido hibernate.cfg e alterado tipo de atributo double para bigdecimal no atributo valor da classe pagamento
> #74 Corrigido o hibernate.cfg

- pom.xml
Corrigida a dependencia do hibernate.
> #77 Corrigida a dependencia hibernate

- pom.xml
- src/main/java/br/edu/ifpe/model/hibernate/UsuarioHibernate.java
- src/main/java/br/edu/ifpe/model/validation/UsuarioModel.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/resources/log4j.xml
Adicionada a dependencia log4j ao pom e adicionado log4j.xml e loggers na classe UsuarioHibernate
> #89 Adicionado logger a classe UsuarioHibernate

- src/main/java/br/edu/ifpe/controller/PagamentoController.java
- src/main/java/br/edu/ifpe/model/classes/Pagamento.java
- src/main/java/br/edu/ifpe/model/hibernate/PagamentoHibernate.java
- src/main/java/br/edu/ifpe/model/validation/PagamentoModel.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/test/java/br/edu/ifpe/model/hibernate/PagamentoHibernateTest.java
- src/test/java/br/edu/ifpe/model/validation/PagamentoModelTest.java
> De acordo a Issue #83.

- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/test/java/br/edu/ifpe/model/hibernate/PagamentoHibernateTest.java
> Conforme a Issue #100

- LICENSE
- README.md
- nb-configuration.xml
- src/main/java/br/edu/ifpe/view/TesteMain.java
Adicionado o nome do Integrante do grupo que faltava na Licença.
> De acordo com a Issue #97

- src/main/java/br/edu/ifpe/controller/UsuarioController.java
Foram adicionados os métodos Login e Logout.
> Conforma a Issue #105

- src/main/java/br/edu/ifpe/model/hibernate/UsuarioHibernate.java
- src/main/java/br/edu/ifpe/model/validation/UsuarioModel.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/resources/hibernate.cfg.xml
- src/test/java/br/edu/ifpe/model/validation/UsuarioModelTest.java
Corrigidos os testes após correção da validação na classe UsuarioModel
> #122 Corrigidos os testes da classe UsuarioModel e validações

- pom.xml
- src/main/webapp/WEB-INF/web.xml
Foram adicionados as depedências e repositórios do Primefaces nos arquivos pom.xml e web.xml
> Conforme a Issue #124

- pom.xml
Removido a dependência JAVAX, pois estava duplicada.
> De acordo com a Issue #128

- README.md
Foi modificado o local da imagem uml do diagrama classe.
> README modificado

- src/main/java/br/edu/ifpe/controller/FacesConvertLocalDate.java
- src/main/java/br/edu/ifpe/model/validation/UsuarioModel.java
- src/main/webapp/cadastrarUsuario.xhtml
- src/test/java/br/edu/ifpe/model/hibernate/LocacaoHibernateTest.java
- src/test/java/br/edu/ifpe/model/hibernate/PagamentoHibernateTest.java
Foi adicionado uma classe conversora, que converte do formato de retorno de <p:calendar>, que é do tipo String, para o formato aceito pelo LocalDate.
> Conforme a Issue #126

- src/main/java/br/edu/ifpe/controller/UsuarioController.java
- src/main/java/br/edu/ifpe/model/classes/Usuario.java
- src/main/java/br/edu/ifpe/model/hibernate/UsuarioHibernate.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/webapp/cadastrarUsuario.xhtml
- src/main/webapp/login.xhtml
Adicionados os métodos de login no Usuário Controller.
> Conforme a Issue #134

- src/main/java/br/edu/ifpe/model/classes/Usuario.java
- src/test/java/br/edu/ifpe/model/hibernate/LocacaoHibernateTest.java
- src/test/java/br/edu/ifpe/model/hibernate/PagamentoHibernateTest.java
Removido o atributo dos testes também.
> #137 Removido o atributo login da classe Usuario

- nb-configuration.xml
- src/main/java/br/edu/ifpe/controller/UsuarioController.java
- src/main/java/br/edu/ifpe/model/hibernate/UsuarioHibernate.java
- src/main/java/br/edu/ifpe/model/interfacesDao/UsuarioDao.java
- src/main/java/br/edu/ifpe/model/validation/UsuarioModel.java
- src/main/webapp/cadastrarUsuario.xhtml
- src/main/webapp/index.xhtml
- src/main/webapp/login.xhtml
- src/main/webapp/menuUsuario.xhtml
- src/main/webapp/mostrarDadosUsuario.xhtml
- src/main/webapp/telaInicial.xhtml
Adicionado o menu do usuário e a opção de mostrar os dados do usuário.
> De acordo a Issue #137

- src/main/java/br/edu/ifpe/model/classes/Bike.java
- src/main/java/br/edu/ifpe/model/classes/Endereco.java
- src/main/java/br/edu/ifpe/model/classes/Locacao.java
- src/main/java/br/edu/ifpe/model/classes/Pagamento.java
- src/main/java/br/edu/ifpe/model/classes/Usuario.java
- src/main/java/br/edu/ifpe/model/hibernate/UsuarioHibernate.java
- src/main/java/br/edu/ifpe/model/interfacesDao/UsuarioDao.java
- src/main/java/br/edu/ifpe/model/validation/UsuarioModel.java
- src/main/resources/hibernate.cfg.xml
- src/test/java/br/edu/ifpe/model/hibernate/LocacaoHibernateTest.java
- src/test/java/br/edu/ifpe/model/hibernate/PagamentoHibernateTest.java
- src/test/java/br/edu/ifpe/model/hibernate/UsuarioHibernateTest.java
- src/test/java/br/edu/ifpe/model/validation/PagamentoModelTest.java
- src/test/java/br/edu/ifpe/model/validation/UsuarioModelTest.java
- src/test/java/br/edu/ifpe/model/validation/ValidarCpfTest.java
Corrigidos todos os testes,projeto construindo normalmente com todos os testes sem ignore
> #146 corridos todos os testes

- src/main/java/br/edu/ifpe/model/classes/Bike.java
> Conforme a Issue #136

- src/main/java/br/edu/ifpe/controller/UsuarioController.java
- src/main/java/br/edu/ifpe/model/classes/Bike.java
- src/main/webapp/cadastrarBike.xhtml
- src/main/webapp/menuUsuario.xhtml
Está funcionando adicionar Bike.
> Conforme a Issue 154

- src/main/java/br/edu/ifpe/controller/UsuarioController.java
- src/main/java/br/edu/ifpe/model/hibernate/UsuarioHibernate.java
- src/main/java/br/edu/ifpe/model/interfacesDao/UsuarioDao.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/resources/hibernate.cfg.xml
- src/main/webapp/alterarBike.xhtml
- src/main/webapp/alterarDadosUsuario.xhtml
- src/main/webapp/menuUsuario.xhtml
> Conforme a Issue #158

- src/main/java/br/edu/ifpe/controller/UsuarioController.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/resources/hibernate.cfg.xml
- src/main/webapp/alterarBike.xhtml
- src/main/webapp/alterarDadosUsuario.xhtml
- src/main/webapp/menuUsuario.xhtml
> Conforme a Issue #155

- src/main/webapp/mostrarDadosUsuario.xhtml
Adicionado dados da bike em mostrarDadosUsuario.
> Adicionei Dados da bike.

- pom.xml
Adicionando o pom.xml modificado
> Conforme a Issue #171

- src/main/java/br/edu/ifpe/model/classes/Bike.java
- src/main/java/br/edu/ifpe/model/classes/Usuario.java
- src/main/java/br/edu/ifpe/model/hibernate/UsuarioHibernate.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/resources/hibernate.cfg.xml
#158 Corrigido o método de recuperar todas as bikes de um usuário.
> #158 Corrigido o método de recuperar as bikes

- src/main/java/br/edu/ifpe/controller/UsuarioController.java
- src/main/java/br/edu/ifpe/model/classes/Bike.java
- src/main/java/br/edu/ifpe/model/classes/Locacao.java
- src/main/java/br/edu/ifpe/model/validation/UsuarioModel.java
- src/main/resources/hibernate.cfg.xml
- src/main/webapp/listarBike.xhtml
- src/main/webapp/menuUsuario.xhtml
- src/main/webapp/mostrarDadosUsuario.xhtml
- src/test/java/br/edu/ifpe/model/hibernate/LocacaoHibernateTest.java
- src/test/java/br/edu/ifpe/model/hibernate/PagamentoHibernateTest.java
- src/test/java/br/edu/ifpe/model/hibernate/UsuarioHibernateTest.java
Listar as Bikes do User, mostrar os detalhes da bike e alterar dados da bike.
> Issue #158 , #156, #155

- src/main/java/br/edu/ifpe/controller/UsuarioController.java
- src/main/java/br/edu/ifpe/model/validation/UsuarioModel.java
- src/main/java/br/edu/ifpe/view/TesteMain.java
- src/main/webapp/alterarDadosUsuario.xhtml
- src/test/java/br/edu/ifpe/model/hibernate/LocacaoHibernateTest.java
- src/test/java/br/edu/ifpe/model/hibernate/UsuarioHibernateTest.java
- src/test/java/br/edu/ifpe/model/validation/UsuarioModelTest.java
> #184 corrigida o usuario controller

- src/main/java/br/edu/ifpe/model/classes/Locacao.java
- src/main/webapp/menuUsuario.xhtml
- src/main/webapp/mostrarLocacaoCliente.xhtml
- src/main/webapp/mostrarLocacaoLocatario.xhtml
Foram adicionadas duas páginas xhtml, mostrar minhas locações e falta ajeitar a página mostrarLocacaoLocatario.xhtml, pois está mostrando a mesma dados da página mostrarLocacaoCliente.xhtml.
> Conforme a Issue #197
